### PR TITLE
Use imagePullPolicy: IfNotPresent to reduce pod startup times

### PR DESCRIPTION
**Pull request by steezeburger**
This reduces pod startup times and only pulls images if they do not already exist.

### CODE REVIEW

**Comment by SuperFluffy** [comment]
I think this already is the default policy for all the container images listed in this deployment.

**Comment by steezeburger** [comment]
> I think this already is the default policy for all the container images listed in this deployment.

From the docs:
> if you omit the imagePullPolicy field, and you specify the tag for the container image that isn't :latest, the imagePullPolicy is automatically set to IfNotPresent.

The docs do mention this, but I have not seen it work like that in practice. 

Screenshot 2023-07-19 at 3 41 14 PM

**Comment by steezeburger** [comment]
@SuperFluffy 
ahh, since we're using `kind` clusters, the images are deleted from kind's local registry when the cluster is deleted.

I bet it wouldn't pull them if they were loaded with `kind load`.

Maybe @joroshiba should just be aware to have those preloaded when running the demo.

**Comment by steezeburger** [comment]
For posterity:
https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

**Pull request closed without merging**
